version: "3.3"
services:
  es762:
    image: elasticsearch:7.6.2
    ports:
      - "9200:9200"
    environment: 
      - discovery.type=single-node
  esHQ:
    image: elastichq/elasticsearch-hq
    ports:
      - "5000:5000"
